## Source code for [Gramercy](http://www.gramercyapp.com/)

Gramercy lets brands send store credit to shoppers when they Instagram their product.

Using the BigCommerce and Instagram APIs, Gramercy automates sending offer emails, tracking Instagram posts, and creating & sending store credits to shoppers. Brands are given a dashboard to track all posts generated by shoppers using Gramercy.